---
title: "Visualize Results"
author: "Elise Amblard, Hugo Barbot, Florent Chuffart and Magali Richard"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---


```{r label = "header", echo = FALSE, eval = TRUE}
knitr::opts_chunk$set(collapse = TRUE, comment = "", echo = FALSE)

for ( package in c("ggplot2","viridis",'magrittr','dplyr','tidyr') ) {
    if ( !{package %in% installed.packages( ) } ) {
        print(x = paste0("Installation of the package : ", package) )
          install.packages(
              pkgs = package
            , repos = "https://cloud.r-project.org"
          )
    }
    library(package, character.only = TRUE)
}
remove(list = "package")
BiocManager::install("ComplexHeatmap")

```



```{r, include=(FALSE)}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=9, fig.height=6, eval=TRUE, echo=FALSE, results="hide")
options(knitr.duplicate.label = "allow")
```

```{r params}

if (!exists("groundtruth_file"))    {groundtruth_file = "../input/ref/groundtruth_smoothies_fruits.rds"} 
if (!exists("prediction_file"))     {prediction_file =  "../input/res/prediction.rds"       }   

```

```{r read_output}
# prediction = readRDS(prediction_file)
# ground_truth = readRDS(groundtruth_file)
prediction = readRDS(  "../input/ref/groundtruth_smoothies_fruits.rds")
ground_truth = readRDS("../input/res/prediction.rds")
```
## Summary of the prediction

### Heatmap of prediction

```{r Heatmap_pred}
ComplexHeatmap::Heatmap(
  t(prediction),
  col = circlize::colorRamp2(seq(0, 1, length.out = 32), rev(heat.colors(32))),
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  heatmap_legend_param = list(title = "Proportion"),
  column_names_rot = 45
)
```


### Heatmap of the absolute bias/error

```{r abs_bias}

abs_bias = abs(prediction - ground_truth)


colors=viridis::viridis(5)

ComplexHeatmap::Heatmap(
  t(abs_bias),
  col = colorRampPalette(colors)(50),
  cluster_rows = FALSE,
  cluster_columns = FALSE,
  heatmap_legend_param = list(title = "Proportion"),
  column_names_rot = 45
)


# abs_bias_per_cell_type = rowMeans(abs_bias)
# sd_estim_per_cell_type = apply(proportion, 1, sd)

# Comment FCh: please avoid magrittr, dplyr, tidyr do to a simple boxplot.
library(magrittr)
library(ggplot2)
abs_bias %>% t() %>% as.data.frame() %>% 
  tidyr::pivot_longer(
    everything(),
    names_to = "Cell_type",
    values_to = "absolut_bias"
  ) %>% 
  dplyr::mutate(
    Cell_type = factor(Cell_type, levels = rownames(abs_bias))
  ) %>% 
  ggplot() +
  geom_boxplot(aes(x = Cell_type, y = absolut_bias)) +
  labs(
    x = "Cell types",
    y = "Absolut bias",
    title = "Absolut bias for all bulks per cell types for dataset1"
  )




# 
# dim(prediction)
# 
# #image(as.matrix(pred), axes=FALSE, col = cols , ylab = colnames(pred), xlab = rownames(pred))
# 
# 
#     
#     Aerr <- data.frame(
#         abserror = as.numeric(
#             x = abs(x = prediction - ground_truth )
#         )
#       , type = rep(
#             x     = seq_len(length.out = nrow(x = ground_truth ) )
#           , times = ncol(x = ground_truth )
#         )
#       , patient = rep(
#             x    = seq_len(length.out = ncol(x = ground_truth ) )
#           , each = nrow(x = ground_truth ) )
#     )
#     
#     p <- ggplot(
#         data    = Aerr
#       , mapping = aes(x = patient, y = type)
#     ) + {
#         geom_tile(
#             mapping = aes(fill = `abserror`)
#           , colour  = "white"
#         )
#     } + {
#         theme_minimal(base_size = 16)
#     } + {
#         labs(
#             y    = "Cell types"
#           , fill = "Absolute error"
#         )
#     } + { 
#         scale_x_discrete(expand = c(0, 0) )
#     } + {
#         scale_y_discrete(expand = c(0, 0) )
#     } + {
#         theme(
#             axis.text.x = element_text(
#                 angle = 70
#               , vjust = 1
#               , size  = 14
#               , hjust = 1
#             )
#         )
#     } + {
#         coord_fixed( )
#     } + {
#         scale_fill_viridis_c(
#             option    = "plasma"
#           , direction = -1
#         )
#     } + {
#         labs(
#             title = paste0("Detail of the matrice ")
#           , x     = "Samples"
#         )
#     }
#     print(x = p)
    



```

## Summary of scores


- scores      :
```{r scores}

mse_scores = colMeans((prediction - ground_truth)^2)


ggplot() +
  geom_boxplot(aes(x = "dataset1",y = mse_scores), width = 0.5) +
  labs(
    x = element_blank(),
    y = "MSE",
    title = "MSE of beta estimed for all bulks of dataset1"
  )
  
# print(x = scores)
# 
# print(x = "Summary :")
# print(x = summary(object = scores) )
# 
# print(x = "Standard deviation :")
# print(x = sd(x = scores) )
# 
# 
# resMAE <- data.frame(
#     A         = seq_len(length.out = length(x = Aref) )
#   , A.MAE     = scores
#   , methode   = rep(x = "Your method",   times = length(x = Aref) )
#   , datatype  = rep(x = dataType, times = length(x = Aref) )
#   , meth_type = rep(x = "Your method",   times = length(x = Aref) )
# )
# 
# allMAE <- as.data.frame(x = rbind(referenceMAE, resMAE) )
# 
# ggplot(
#     data    = allMAE
#   , mapping = aes(
#         x      = methode
#       , y      = A.MAE
#       , fill   = meth_type
#       , colour = datatype
#     )
# ) + {
#     geom_boxplot(
#         notch = FALSE
#     )
# } + {
#     ## stat_summary(
#     ##     fun.y = mean
#     ##   , geom  = "point"
#     ##   , shape = 23
#     ##   , size  = 3
#     ## )
# } + {
#     geom_dotplot(
#         binaxis  = 'y'
#       , stackdir = 'center'
#       , dotsize  = 0.25
#     )
# } + {
#     scale_x_discrete(
#         limits = levels(x = allMAE$method)[
#             order(
#                 sapply(
#                     X   = levels(x = allMAE$method)
#                   , FUN = function( m ) {
#                       mean(x = allMAE[allMAE$method == m, "A.MAE"] )
#                   }
#                 )
#               , decreasing = TRUE
#             )
#         ]
#     )
# } + {
#     ylim(0, 0.15)
# } + {
#     theme_minimal(base_size = 16)
# } + {
#     theme(
#         axis.text.x  = element_text(
#             angle = 70
#           , vjust = 1
#           , hjust = 1
#           , size  = 14
#         )
#     )
# } + {
#     scale_fill_manual(
#         breaks = c("Reference", "Your method")
#       , values = c("white",     "#cc0000"    )
#     )
# } + {
#     scale_colour_manual(
#         breaks = c("both",    "met",    "rna",     as.character(x = resMAE$datatype[ 1 ] ) )
#       , values = c("#23A900", "#4886FE", "#FED248", switch(EXPR = dataType, "both" = "#23A900", "met" = "#4886FE", "rna" = "#FED248") )
#     )
# } + {
#     labs(
#         title  = ""
#       , x      = "Methods"
#       , y      = "MAE"
#       , colour = "Data type"
#       , fill   = "Method type"
#     )
# }
```

